--
-- PostgreSQL database dump
--

\restrict g2ioPcttuKldc2MN6FfgcoZrV7NQNIsZgcLPyz6ZCuPi7msW5yY6pROEGUpAq2I

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: workposition; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workposition (
    work_id integer NOT NULL,
    work_type character varying(60),
    work_name character varying(200)
);


ALTER TABLE public.workposition OWNER TO postgres;

--
-- Name: workposition_work_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workposition ALTER COLUMN work_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workposition_work_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: workposition; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workposition (work_id, work_type, work_name) FROM stdin;
\.


--
-- Name: workposition_work_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.workposition_work_id_seq', 1, false);


--
-- Name: workposition workposition_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workposition
    ADD CONSTRAINT workposition_pkey PRIMARY KEY (work_id);


--
-- PostgreSQL database dump complete
--

\unrestrict g2ioPcttuKldc2MN6FfgcoZrV7NQNIsZgcLPyz6ZCuPi7msW5yY6pROEGUpAq2I

