-- create database books_deals;
\c books_deals

create table if not exists authors(
    code_author int generated by default as identity primary key ,
    name varchar(150),
    Birthday timestamp
);

create table if not exists publishing_houses(
    code_publish int generated by default as identity primary key ,
    publish varchar(90),
    city varchar(40)
);

create table if not exists books(
    code_book int generated by default as identity primary key,
    title_book varchar(100),
    code_author int references authors(code_author),
    pages int,
    code_publish int references publishing_houses(code_publish)
);

create table if not exists deliveries(
    code_delivery int generated by default as identity primary key ,
    name_company varchar(120),
    address varchar(200),
    phone bigint,
    INN bigint
);

create table if not exists purshases(
    code_book int references books(code_book),
    date_order timestamp,
    code_delivery int references deliveries(code_delivery),
    type_purchase varchar(40),
    cost int,
    amount int,
    code_purchase int generated by default as identity primary key
);

