version: "latest"
services:
  db:
    build: .
    container_name: cursovoi-db-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cursovoi_project
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
